### ISSUE TITLE
how to make host groups

### ISSUE THREAD

**Issue by montells** [volanja/ansible-sample-tdd#2]
I want to run differente test for differente host

[ubuntu]
172.23.10.22 ansible_ssh_host=172.23.10.22 ansible_ssh_user=test ansible_ssh_pass=test

[centos]
172.23.10.23 ansible_ssh_host=172.23.10.23 ansible_ssh_user=test ansible_ssh_pass=test

[other]
172.23.10.24 ansible_ssh_host=172.23.10.24 ansible_ssh_user=test ansible_ssh_pass=test

[pg]
ubuntu
centos

[mail]
other
ubuntu
centos

my site.yml

- name: pg
  hosts: pg
  roles:
    - pg

- name: mail
  hosts: mail
  roles:
    - mail

I want rake:pg run in ubuntu and centos hosts and rake:mail run in all hosts. 

Therefore I need spec for centos are differents of test for ubuntu. It is possible? How?

**Comment by volanja** [comment]
I update `ansible_spec`.
Please install `ansible_spec` that Rubygems.
And you should change files.

```inventory
[ubuntu]
172.23.10.22 ansible_ssh_host=172.23.10.22 ansible_ssh_user=test

[centos]
172.23.10.23 ansible_ssh_host=172.23.10.23 ansible_ssh_user=test

[other]
172.23.10.24 ansible_ssh_host=172.23.10.24 ansible_ssh_user=test

[pg:children]
ubuntu
centos

[mail:children]
other
ubuntu
centos
```

(Not Support ansible_ssh_pass. it's [insecure](http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters))

```site.yml
- name: pg
  hosts: pg
  user: root
  roles:
    - pg

- name: mail
  hosts: mail
  user: root
  roles:
    - mail
```
